version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: prakashsellathurai.github.io
    path: ""
    text-resources:
      - path: ""
        format: flat-key-value
