
title: Prakash S
email: prakashsellathurai@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: prakash1729brt
github_username:  prakashsellathurai



collections:
  posts:
    title: essays
    output: true
    permalink: essay/:title



projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  # limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
# Build settings

plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji


feed:
  excerpt_only: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
